version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: amc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amc_workforce
    ports:
      - '5432:5432'
    volumes:
      - amc_pgdata:/var/lib/postgresql/data

volumes:
  amc_pgdata:
