import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

const HR_EMAIL = process.env.HR_EMAIL ?? 'hr@accramedical.com'
const RESEND_API_KEY = process.env.RESEND_API_KEY

export async function POST(req: NextRequest) {
  const { month, year } = await req.json()

  if (!RESEND_API_KEY) {
    return NextResponse.json({ error: 'RESEND_API_KEY not configured. Add it to Vercel environment variables.' }, { status: 500 })
  }

  // Fetch non-compliant data for the month
  const monthStart = new Date(year, month - 1, 1)
  const monthEnd   = new Date(year, month, 0)

  let nonCompliant: { name: string; dept: string; noShows: number; lateCount: number }[] = []
  try {
    const employees  = await prisma.employee.findMany({ where: { status: 'ACTIVE' }, select: { id: true, name: true, departmentId: true, department: { select: { name: true } } } })
    const attendance = await prisma.attendance.findMany({
      where: { date: { gte: monthStart, lte: monthEnd } },
      select: { employeeId: true, status: true, lateMinutes: true },
    })

    const empMap = new Map(employees.map(e => [e.id, e]))
    const grouped = new Map<string, { noShows: number; lateCount: number }>()
    for (const a of attendance) {
      const cur = grouped.get(a.employeeId) ?? { noShows: 0, lateCount: 0 }
      if (a.status === 'ABSENT') cur.noShows++
      if ((a.lateMinutes ?? 0) > 0) cur.lateCount++
      grouped.set(a.employeeId, cur)
    }

    nonCompliant = Array.from(grouped.entries())
      .filter(([, v]) => v.noShows > 0 || v.lateCount > 2)
      .map(([empId, v]) => {
        const emp = empMap.get(empId)
        return { name: emp?.name ?? empId, dept: (emp as any)?.department?.name ?? '—', ...v }
      })
      .sort((a, b) => b.noShows - a.noShows)
      .slice(0, 30)
  } catch (e) {
    return NextResponse.json({ error: String(e) }, { status: 500 })
  }

  const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December']
  const monthName = MONTHS[month - 1]

  const rows = nonCompliant.map(e =>
    `<tr><td style="padding:6px 12px;border-bottom:1px solid #f0f0f0">${e.name}</td><td style="padding:6px 12px;border-bottom:1px solid #f0f0f0">${e.dept}</td><td style="padding:6px 12px;border-bottom:1px solid #f0f0f0;color:#dc2626;font-weight:600">${e.noShows}</td><td style="padding:6px 12px;border-bottom:1px solid #f0f0f0;color:#d97706">${e.lateCount}</td></tr>`
  ).join('')

  const html = `
    <div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto">
      <div style="background:#0f1117;padding:24px 32px;border-radius:8px 8px 0 0">
        <h1 style="color:#f59e0b;margin:0;font-size:20px">AMC Hospital — Non-Compliance Alert</h1>
        <p style="color:rgba(255,255,255,0.5);margin:4px 0 0;font-size:13px">${monthName} ${year} · Generated by Workforce System</p>
      </div>
      <div style="background:#fff;padding:24px 32px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px">
        <p style="color:#374151;font-size:14px">The following staff members have been flagged for non-compliance in <strong>${monthName} ${year}</strong> — either for absences or repeated late arrivals (3+ occurrences).</p>
        ${nonCompliant.length === 0 ? '<p style="color:#16a34a;font-weight:600">No non-compliance issues found this month.</p>' : `
        <table style="width:100%;border-collapse:collapse;font-size:13px;margin-top:16px">
          <thead>
            <tr style="background:#f9fafb">
              <th style="padding:8px 12px;text-align:left;color:#6b7280;font-weight:600;border-bottom:2px solid #e5e7eb">Name</th>
              <th style="padding:8px 12px;text-align:left;color:#6b7280;font-weight:600;border-bottom:2px solid #e5e7eb">Department</th>
              <th style="padding:8px 12px;text-align:left;color:#dc2626;font-weight:600;border-bottom:2px solid #e5e7eb">Absences</th>
              <th style="padding:8px 12px;text-align:left;color:#d97706;font-weight:600;border-bottom:2px solid #e5e7eb">Late Arrivals</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
        <p style="color:#6b7280;font-size:12px;margin-top:16px">Total flagged: <strong>${nonCompliant.length} staff members</strong>. Please review and take appropriate action.</p>
        `}
        <p style="color:#9ca3af;font-size:11px;margin-top:24px;border-top:1px solid #f0f0f0;padding-top:12px">This is an automated notification from the AMC Workforce Management System. Do not reply to this email.</p>
      </div>
    </div>
  `

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${RESEND_API_KEY}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      from: 'AMC Workforce <onboarding@resend.dev>',
      to: [HR_EMAIL],
      subject: `[AMC] Non-Compliance Report — ${monthName} ${year}`,
      html,
    }),
  })

  if (!res.ok) {
    const err = await res.text()
    return NextResponse.json({ error: `Resend error: ${err}` }, { status: 500 })
  }

  return NextResponse.json({ message: `Non-compliance report sent to ${HR_EMAIL} (${nonCompliant.length} staff flagged)` })
}
